export const SEARCH_CONTENT = 'SEARCH_CONTENT';
export const SEARCH_CONTENT_SUCCESS = 'SEARCH_CONTENT_SUCCESS';
export const SEARCH_CONTENT_FAILED = 'SEARCH_CONTENT_FAILED';
export const CLEAR_SEARCH_CONTENT = 'CLEAR_SEARCH_CONTENT';

export const SEARCH_CONTENT_META = 'SEARCH_CONTENT_META';
export const SEARCH_CONTENT_META_SUCCESS = 'SEARCH_CONTENT_META_SUCCESS';
export const SEARCH_CONTENT_META_FAILED = 'SEARCH_CONTENT_META_FAILED';
