export const GET_ALL_ARTICAL = 'GET_ALL_ARTICAL';
export const GET_ALL_ARTICAL_SUCCESS = 'GET_ALL_ARTICAL_SUCCESS';
export const GET_ALL_ARTICAL_FAILED = 'GET_ALL_ARTICAL_FAILED';
export const CLEAR_ALL_ARTICLE = 'CLEAR_ALL_ARTICLE';

export const REFRESH_GET_ALL_ARTICAL = 'REFRESH_GET_ALL_ARTICAL';
export const REFRESH_GET_ALL_ARTICAL_FAILED = 'REFRESH_GET_ALL_ARTICAL_FAILED';
export const REFRESH_GET_ALL_ARTICAL_SUCCESS =
  'REFRESH_GET_ALL_ARTICAL_SUCCESS';
export const SET_REFRESH_FALSE = 'SET_REFRESH_FALSE';

export const GET_EACH_ARTICAL = 'GET_EACH_ARTICAL';
export const GET_EACH_ARTICAL_SUCCESS = 'GET_EACH_ARTICAL_SUCCESS';
export const GET_EACH_ARTICAL_FAILED = 'GET_EACH_ARTICAL_FAILED';

export const GET_FEATURED_ARTICAL = 'GET_FEATURED_ARTICAL';
export const GET_FEATURED_ARTICAL_SUCCESS = 'GET_FEATURED_ARTICAL_SUCCESS';
export const GET_FEATURED_ARTICAL_FAILED = 'GET_FEATURED_ARTICAL_FAILED';
