export const GET_CATEGORIZED_ARTICAL = 'GET_CATEGORIZED_ARTICAL';
export const GET_CATEGORIZED_ARTICAL_SUCCESS =
  'GET_CATEGORIZED_ARTICAL_SUCCESS';
export const GET_CATEGORIZED_ARTICAL_FAILED = 'GET_CATEGORIZED_ARTICAL_FAILED';
export const CLEAR_CATEGORIZED_ARTICAL = 'CLEAR_CATEGORIZED_ARTICAL';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_ALL_CATEGORY_SUCCESS = 'GET_ALL_CATEGORY_SUCCESS';
export const GET_ALL_CATEGORY_FAILED = 'GET_ALL_CATEGORY_FAILED';
export const GET_ALL_AUTH_CATEGORY = 'GET_ALL_AUTH_CATEGORY';

export const SET_CATEGORY = 'SET_CATEGORY';
