export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const CONFIRM_SIGN_UP = 'CONFIRM_SIGN_UP';
export const SIGN_UP_CONFIRMED = 'SIGN_UP_CONFIRMED';
export const SIGN_UP_CONFIRMED_FAILED = 'SIGN_UP_CONFIRMED_FAILED';

export const SIGN_IN = 'SIGN_IN';
export const FEDERATED_SIGN_IN = 'FEDERATED_SIGN_IN';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_USERNAME = 'GET_USERNAME';

export const CLEAR_AUTH = 'CLEAR_AUTH';

export const SET_USER = 'SET_USER';
export const SET_UP_USER = 'SET_UP_USER';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const USER_KEY = 'user_key';
