export const GET_USER_LANGUAGE = 'GET_USER_LANGUAGE';
export const CHANGE_USER_LANGUAGE = 'CHANGE_USER_LANGUAGE';
export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_FONTSIZE = 'CHANGE_FONTSIZE';
export const CHANGE_BACKGROUND_TYPE = 'CHANGE_BACKGROUND_TYPE';
